name: Lint, Build, Deploy HTML, and Push Docker Image

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install htmlhint
        run: npm install -g htmlhint

      - name: Lint HTML
        run: htmlhint index.html

  build-htmls:
    runs-on: ubuntu-latest
    needs: lint-html
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v3

      - name: Prepare HTML output
        run: |
          mkdir -p output
          cp index.html output/index.html

      - name: Upload HTMLs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-html
          path: output

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-htmls
    if: github.ref_name == 'master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: output-html
          path: created_htmls

      - name: List downloaded stuff
        run: ls -al created_htmls

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: created_htmls

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  docker-push:
    runs-on: ubuntu-latest
    needs: lint-html
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${BRANCH_NAME}-latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${BRANCH_NAME}-latest
